<?php

/**
 * @file
 * System 4xx module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function digitalconvergence_4xx_theme($existing, $type, $theme, $path) {
  $config = \Drupal::configFactory()->getEditable('system.site');
  return [
    'digitalconvergence_4xx' => [
      'template' => 'digitalconvergence-4xx',
      'variables' => [],
    ],
    'digitalconvergence_403' => [
      'template' => 'digitalconvergence-403',
      'variables' => [],
    ],
    'digitalconvergence_404' => [
      'template' => 'digitalconvergence-404',
      'variables' => [
        'page_404_title' => $config->get('page.404_title'),
        'page_404_body' => $config->get('page.404_body'),
      ],
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function digitalconvergence_4xx_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'system_site_information_settings') === 0) {
    // Deny access to default 4xx site settings.
    $form['error_page']['site_403'] = [
      '#access' => FALSE,
    ];
    $form['error_page']['site_404'] = [
      '#access' => FALSE,
    ];
    // Add options and submit handler for 404 error page custom content.
    $config = \Drupal::configFactory()->getEditable('system.site');
    $form['error_page']['site_404_content'] = [
      '#type' => 'fieldset',
      '#title' => t('404 (not found) page'),
      'site_404_content_title' => [
        '#type' => 'textfield',
        '#title' => t('404 (not found) page title'),
        '#default_value' => $config->get('page.404_title'),
      ],
      'site_404_content_body' => [
        '#type' => 'text_format',
        '#title' => t('404 (not found) page body'),
        '#default_value' => $config->get('page.404_body'),
      ],
    ];
    $form['actions']['submit']['#submit'][] = 'digitalconvergence_4xx_system_site_information_settings_submit';
  }
}

/**
 * Site Information Settings form custom submit handler.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form. The arguments that \Drupal::formBuilder()->getForm() was originally called with
 *   are available in the array $form_state->getBuildInfo()['args'].
 */
function digitalconvergence_4xx_system_site_information_settings_submit(array $form, FormStateInterface $form_state) {
  $site_404_title = $form_state->getValues()['site_404_content_title'];
  $site_404_content_body = $form_state->getValues()['site_404_content_body']['value'];
  \Drupal::configFactory()
    ->getEditable('system.site')
    ->set('page.404_title', $site_404_title)
    ->set('page.404_body', $site_404_content_body)
    ->save();
}

